#!/bin/bash
# Quick Docker Compose Commands Cheat Sheet

echo "📋 Reddit Hate Speech Detection - Docker Commands"
echo "=================================================="
echo ""
echo "🔹 Single Run (runs once and stops):"
echo "   docker-compose --profile single up"
echo ""
echo "🔹 Scheduler Mode (every 2 hours, background):"
echo "   docker-compose --profile scheduler up -d"
echo ""
echo "🔹 Continuous Mode (every 5 minutes, background):"
echo "   docker-compose --profile continuous up -d"
echo ""
echo "🔹 API Only (default, no profile needed):"
echo "   docker-compose up -d"
echo ""
echo "🛑 Stop Everything:"
echo "   docker-compose down"
echo ""
echo "📊 View Logs:"
echo "   docker-compose logs -f reddit-scraper"
echo "   docker-compose logs -f api"
echo ""
echo "🔍 Check Status:"
echo "   docker-compose ps"
echo ""
echo "🔨 Rebuild:"
echo "   docker-compose build"
echo ""
echo "=================================================="
echo ""
echo "💡 Tips:"
echo "   • Use --profile <mode> to select execution mode"
echo "   • API always starts by default"
echo "   • For local runs: python -m src.main"
echo ""

